### ISSUE TITLE
How do i install the adapter in IoBroker?

### ISSUE THREAD

**Issue by NikoTheBoss** [husky-koglhof/ioBroker.homekit#5]
Hello,
i just started to work with the IoBroker and i tried to install the adapter but it didn't work, could you be so kind and explain ist step by step?

kind regards 
Niko

**Comment by husky-koglhof** [comment]
Hi Niko, do you speak german or english?

I'm from Austria, if you can't speak or write in german, we can communicate in english.

First of all, after installation of iobroker.homekit, did you get some errors in the iobroker log?

Did you see anything in homekit?

Kind regards
Christian

**Comment by NikoTheBoss** [comment]
Danke für die Antwort,
Meine schritte die ich gemacht habe waren so:
1. URL von der Seite kopieren (https://github.com/husky-koglhof/ioBroker.homekit/)
<img width="1017" alt="bildschirmfoto 2016-01-07 um 20 13 05" src="https://cloud.githubusercontent.com/assets/16563292/12180188/6ad4dc76-b57b-11e5-8631-580d7bf35f42.png">
2. Addon über URL installieren
<img width="668" alt="bildschirmfoto 2016-01-07 um 20 13 29" src="https://cloud.githubusercontent.com/assets/16563292/12180216/95ad1d28-b57b-11e5-8b8a-7a1f878fd626.png">
3. diese Fehler Meldung wurde gezeigt.
$ ./iobroker url "https://github.com/husky-koglhof/ioBroker.homekit.git"
install https://github.com/husky-koglhof/ioBroker.homekit.git/tarball/master
npm install https://github.com/husky-koglhof/ioBroker.homekit.git/tarball/master --production --prefix "/opt/iobroker" (System call)
npm

http
 GET
 https://github.com/husky-koglhof/ioBroker.homekit.git/tarball/master
npm http 404 https://github.com/husky-koglhof/ioBroker.homekit.git/tarball/master
npm ERR! fetch failed https://github.com/husky-koglhof/ioBroker.homekit.git/tarball/master
npm ERR!
 Error: 404 Not Foundnpm ERR!     at WriteStream.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/fetch.js:57:12)
npm ERR!     at WriteStream.EventEmitter.emit (events.js:117:20)
npm ERR!     at fs.js:1596:14
npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:103:5
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm
 ERR!     http://github.com/isaacs/npm/issuesnpm ERR! or email it to:
npm ERR!     npm-@googlegroups.com

npm ERR! System Linux 4.1.13-v7+
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "https://github.com/husky-koglhof/ioBroker.homekit.git/tarball/master" "--production" "--prefix" "/opt/iobroker"
npm ERR! cwd /opt
npm ERR! node -v v0.10.22
npm ERR! npm -v 1.3.14

npm ERR! npm ERR! Additional logging details can be found in:
npm ERR!     /opt/npm-debug.log
npm ERR! not ok code 0

ERROR: host.raspberrypi Cannot install https://github.com/husky-koglhof/ioBroker.homekit.git/tarball/master: 1
ERROR: process exited with code 25

bin ich komplett auf dem Falschen weg?
danke schon mal für die Unterstützung

**Comment by husky-koglhof** [comment]
Guten Morgen!

Probier mal diese URL aus: https://github.com/husky-koglhof/ioBroker.homekit/tarball/master
Diese URL's werden normalerweise auch direkt in der Commandline verwendet.

LG Christian

**Comment by NikoTheBoss** [comment]
Moin, 
was meinst du mit Commandaline? 
ich habe den neuen Link wieder über Addon über URL installieren,
Die Installation lief etwas länger aber am ende gab es den folgenden Fehler.

$ ./iobroker url "https://github.com/husky-koglhof/ioBroker.homekit/tarball/master" --debug
install https://github.com/husky-koglhof/ioBroker.homekit/tarball/master
npm install https://github.com/husky-koglhof/ioBroker.homekit/tarball/master --production --prefix "/opt/iobroker" (System call)
npm
 http GET https://github.com/husky-koglhof/ioBroker.homekit/tarball/master
npm 
http 200 https://github.com/husky-koglhof/ioBroker.homekit/tarball/master
npm
 http 
GET https://registry.npmjs.org/hap-nodejs
npm
 http GET https://registry.npmjs.org/yalm
npm http GET https://registry.npmjs.org/yargs
npm
 http 304 https://registry.npmjs.org/yargs
npm
 http 304 https://registry.npmjs.org/hap-nodejs
npm http 304 https://registry.npmjs.org/yalm
npm http GET https://registry.npmjs.org/ansi-styles
npm
 http 304 https://registry.npmjs.org/ansi-styles
npm http GET https://registry.npmjs.org/decamelize
npm http GET https://registry.npmjs.org/window-size
npm http GET https://registry.npmjs.org/y18n
npm http GET https://registry.npmjs.org/string-width
npm http GET https://registry.npmjs.org/camelcase
npm http GET https://registry.npmjs.org/cliui
npm http GET https://registry.npmjs.org/os-locale
npm http 304 https://registry.npmjs.org/window-size
npm http 304 https://registry.npmjs.org/y18n
npm http 304 https://registry.npmjs.org/decamelize
npm http 304 https://registry.npmjs.org/camelcase
npm http 304 https://registry.npmjs.org/os-locale
npm http 304 https://registry.npmjs.org/cliui
npm http 304 https://registry.npmjs.org/string-width
npm http GET https://registry.npmjs.org/debug
npm http GET https://registry.npmjs.org/mdns
npm http GET https://registry.npmjs.org/node-persist
npm http 304 https://registry.npmjs.org/debug
npm
 http 304 https://registry.npmjs.org/mdns
npm http 304 https://registry.npmjs.org/node-persist
npm
 http GET https://registry.npmjs.org/escape-string-regexp
npm
 http 
GET
 https://registry.npmjs.org/code-point-at
npm
 http 
GET
 https://registry.npmjs.org/is-fullwidth-code-point
npm
 http

GET https://registry.npmjs.org/strip-ansi
npm
 http 
GET https://registry.npmjs.org/lcid
npm
 http 304 https://registry.npmjs.org/escape-string-regexp
npm
 http 304 https://registry.npmjs.org/code-point-at
npm http 304 https://registry.npmjs.org/is-fullwidth-code-point
npm http 304 https://registry.npmjs.org/strip-ansi
npm http 304 https://registry.npmjs.org/lcid
npm
 http GET https://registry.npmjs.org/number-is-nan
npm http GET
 https://registry.npmjs.org/ansi-regex
npm http 304 https://registry.npmjs.org/ansi-regex
npm http GET https://registry.npmjs.org/invert-kv
npm http GET https://registry.npmjs.org/wrap-ansi
npm http 304 https://registry.npmjs.org/invert-kv
npm http 304 https://registry.npmjs.org/wrap-ansi
npm
 http 304 https://registry.npmjs.org/number-is-nan
npm
 http GET https://registry.npmjs.org/nan
npm
 http GET https://registry.npmjs.org/bindings
npm
 http 
304 https://registry.npmjs.org/nan
npm http 304 https://registry.npmjs.org/bindings
npm
 http GET
 https://registry.npmjs.org/ms/0.7.1
npm
 http 304 https://registry.npmjs.org/ms/0.7.1
npm
 http GET https://registry.npmjs.org/mkdirp
npm
 http GET https://registry.npmjs.org/q
npm
 http 304 https://registry.npmjs.org/mkdirp
npm
 http 304 https://registry.npmjs.org/q
npm
 http GET https://registry.npmjs.org/bignum/0.11.0
npm
 http 304 https://registry.npmjs.org/bignum/0.11.0

> curve25519@1.1.0 install /opt/iobroker/node_modules/iobroker.homekit/node_modules/hap-nodejs/node_modules/curve25519
> node-gyp rebuild

make: Entering directory '/opt/iobroker/node_modules/iobroker.homekit/node_modules/hap-nodejs/node_modules/curve25519/build'
  CXX(target) Release/obj.target/curve/node_curve.o
  SOLINK_MODULE(target) Release/obj.target/curve.node
  SOLINK_MODULE(target) Release/obj.target/curve.node: Finished
  COPY Release/curve.node
make: Leaving directory '/opt/iobroker/node_modules/iobroker.homekit/node_modules/hap-nodejs/node_modules/curve25519/build'

> bignum@0.11.0 install /opt/iobroker/node_modules/iobroker.homekit/node_modules/hap-nodejs/node_modules/srp/node_modules/bignum
> node-gyp configure build

make: Entering directory '/opt/iobroker/node_modules/iobroker.homekit/node_modules/hap-nodejs/node_modules/srp/node_modules/bignum/build'
  CXX(target) Release/obj.target/bignum/bignum.o
  SOLINK_MODULE(target) Release/obj.target/bignum.node
  SOLINK_MODULE(target) Release/obj.target/bignum.node: Finished
  COPY Release/bignum.node
make: Leaving directory '/opt/iobroker/node_modules/iobroker.homekit/node_modules/hap-nodejs/node_modules/srp/node_modules/bignum/build'

> mdns@2.2.11 install /opt/iobroker/node_modules/iobroker.homekit/node_modules/hap-nodejs/node_modules/mdns
> node-gyp rebuild

make: Entering directory '/opt/iobroker/node_modules/iobroker.homekit/node_modules/hap-nodejs/node_modules/mdns/build'
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_sd.o
In file included from ../src/dns_sd.cpp:1:0:../src/mdns.hpp:32:20: fatal error: dns_sd.h: No such file or directory
compilation terminated.

dns_sd_bindings.target.mk:130: recipe for target 'Release/obj.target/dns_sd_bindings/src/dns_sd.o' failedmake: Leaving directory '/opt/iobroker/node_modules/iobroker.homekit/node_modules/hap-nodejs/node_modules/mdns/build'

make: **\* [Release/obj.target/dns_sd_bindings/src/dns_sd.o] Error 1
gyp
 ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2gyp ERR!
 stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR!
 stack     at Process.ChildProcess._handle.onexit (child_process.js:789:12)gyp ERR! System Linux 4.1.13-v7+

gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"gyp ERR! cwd /opt/iobroker/node_modules/iobroker.homekit/node_modules/hap-nodejs/node_modules/mdns
gyp ERR! node -v v0.10.22
gyp ERR! node-gyp -v v0.11.0

gyp ERR! not ok 

> ed25519@0.0.3 install /opt/iobroker/node_modules/iobroker.homekit/node_modules/hap-nodejs/node_modules/ed25519
> node-gyp rebuild

node.js:810
    var cwd = process.cwd();

```
         ^
```

Error: ENOENT, no such file or directory    at Function.startup.resolveArgv0 (node.js:810:23)
    at startup (node.js:58:13)
    at node.js:901:3

npm

ERR! mdns@2.2.11 install: `node-gyp rebuild`npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mdns@2.2.11 install script.

npm ERR! This is most likely a problem with the mdns package,npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!
     node-gyp rebuildnpm ERR! You can get their info via:
npm ERR!     npm owner ls mdns
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 4.1.13-v7+
npm ERR!
 command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "https://github.com/husky-koglhof/ioBroker.homekit/tarball/master" "--production" "--prefix" "/opt/iobroker"npm ERR! cwd /opt
npm ERR! node -v v0.10.22
npm
 ERR! npm -v 1.3.14npm ERR! code ELIFECYCLE

npm ERR! npm 
ERR! Additional logging details can be found in:npm ERR!     /opt/npm-debug.log
npm ERR! not ok code 0

ERROR: host.raspberrypi Cannot install https://github.com/husky-koglhof/ioBroker.homekit/tarball/master: 1
ERROR: process exited with code 25

**Comment by NikoTheBoss** [comment]
ich habe es mal über den Terminal versucht,
da kommt dieser Fehler 
make: Entering directory '/root/node_modules/iobroker.homekit/node_modules/hap-nodejs/node_modules/mdns/build'
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_sd.o
In file included from ../src/dns_sd.cpp:1:0:
../src/mdns.hpp:32:20: fatal error: dns_sd.h: No such file or directory
compilation terminated.
dns_sd_bindings.target.mk:130: recipe for target 'Release/obj.target/dns_sd_bindings/src/dns_sd.o' failed
make: **\* [Release/obj.target/dns_sd_bindings/src/dns_sd.o] Error 1
make: Leaving directory '/root/node_modules/iobroker.homekit/node_modules/hap-nodejs/node_modules/mdns/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:789:12)
gyp ERR! System Linux 4.1.13-v7+
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /root/node_modules/iobroker.homekit/node_modules/hap-nodejs/node_modules/mdns
gyp ERR! node -v v0.10.22
gyp ERR! node-gyp -v v0.11.0
gyp ERR! not ok 
npm ERR! mdns@2.2.11 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mdns@2.2.11 install script.
npm ERR! This is most likely a problem with the mdns package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls mdns
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 4.1.13-v7+
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "https://github.com/husky-koglhof/ioBroker.homekit/tarball/master"
npm ERR! cwd /root
npm ERR! node -v v0.10.22
npm ERR! npm -v 1.3.14
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /root/npm-debug.log
npm ERR! not ok code 0

**Comment by Apollon77** [comment]
When I remember correctly you need node 0.12.x for hap-nodejs to work and compile correctly!! Yu only have node 0.10.22

**Comment by husky-koglhof** [comment]
Dies sieht nach einer Abhängigkeit zu mdns aus:

Siehe hierzu: https://github.com/KhaosT/HAP-NodeJS/wiki/Installing (Punkt 1)

LG Christian

**Comment by NikoTheBoss** [comment]
jetzt habe ich alles neue aufgesetzt und bekomme jetzt folgenden Fehler code
$ ./iobroker url "https://github.com/KhaosT/HAP-NodeJS/wiki/Installing"
install https://github.com/KhaosT/HAP-NodeJS/wiki/Installing/tarball/master
npm install https://github.com/KhaosT/HAP-NodeJS/wiki/Installing/tarball/master --production --prefix "/opt/iobroker" (System call)
npm
 ERR! fetch failed https://github.com/KhaosT/HAP-NodeJS/wiki/Installing/tarball/master
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 406
npm
 ERR! 
fetch failed https://github.com/KhaosT/HAP-NodeJS/wiki/Installing/tarball/master
npm WARN 
retry will retry, error on last attempt: Error: fetch failed with status code 406

danke aber schon mal für eure Unterstützung

**Comment by NikoTheBoss** [comment]
Ich hatte in meinen ersten post den falschen Link,
jetzt kommt wieder der folgende Fehler 
$ ./iobroker url "https://github.com/husky-koglhof/ioBroker.homekit/tarball/master"
install https://github.com/husky-koglhof/ioBroker.homekit/tarball/master
npm install https://github.com/husky-koglhof/ioBroker.homekit/tarball/master --production --prefix "/opt/iobroker" (System call)
In file included from ../src/dns_sd.cpp:1:0:../src/mdns.hpp:32:20: fatal error: dns_sd.h: No such file or directory
compilation terminated.

make: **\* [Release/obj.target/dns_sd_bindings/src/dns_sd.o] Error 1
gyp

ERR! build error 
gyp
 ERR! stack Error: `make` failed with exit code: 2gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)

gyp ERR! stack     at ChildProcess.emit (events.js:110:17)gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Linux 3.18.11-v7+

gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"gyp ERR! cwd /opt/iobroker/node_modules/iobroker.homekit/node_modules/hap-nodejs/node_modules/mdns
gyp ERR! node -v v0.12.6
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok 

npm

ERR! Linux 3.18.11-v7+
npm 
ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "https://github.com/husky-koglhof/ioBroker.homekit/tarball/master" "--production" "--prefix" "/opt/iobroker"npm ERR! node v0.12.6
npm ERR! npm  v2.11.2
npm ERR!
 code ELIFECYCLE
npm ERR! mdns@2.2.11 install: `node-gyp rebuild`

npm ERR! Exit status 1npm ERR! 
npm ERR! Failed at the mdns@2.2.11 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the mdns package,
npm ERR!
 not with npm itself.npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm
 ERR! You can get their info via:npm ERR!     npm owner ls mdns
npm ERR! There is likely additional logging output above.

npm
 ERR!
 Please include the following file with any support request:npm 
ERR!     /opt/iobroker/node_modules/npm-debug.log
ERROR: host.raspberrypi Cannot install https://github.com/husky-koglhof/ioBroker.homekit/tarball/master: 1
ERROR: process exited with code 25

**Comment by NikoTheBoss** [comment]
Läuft :-)

**Comment by husky-koglhof** [comment]
Was hast du jetzt gemacht, das es funktioniert?

LG Christian

**Comment by NikoTheBoss** [comment]
Ich habe einfach alles noch mal neu aufgesetzt.
Aber wo am Ende das anfängliche Problem lag kann ich nicht genau sagen.

Gruß 
Niko
