### ISSUE TITLE
Kann Adapter aus iobroker heraus nicht installieren

### ISSUE THREAD

**Issue by aski71** [husky-koglhof/ioBroker.homekit#7]
Hallo,

wenn ich über das "+" in der ioBroker Admin-Oberfläche homekit installieren will, passiert folgendes:

$ ./iobroker add homekit
npm install iobroker.homekit --production --prefix "/share/MD0_DATA/alex/iobroker" (System call)
gyp
 ERR!
 configure error

gyp ERR! stack Error: Command failed: /usr/local/bin/python2 -c import platform; print(platform.python_version());
gyp ERR! stack Traceback (most recent call last):gyp ERR! stack   File "<string>", line 1, in <module>
gyp ERR! stack   File "/root/daily_build/4.2.0/Model/TS-459/../../SysUtil/Python-2.7.5-cross/install_path_full/lib/python2.7/platform.py", line 116, in <module>
gyp ERR! stack ImportError: No module named string
gyp ERR! stack 
gyp 
ERR! stack     at ChildProcess.exithandler (child_process.js:213:12)gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:827:16)

gyp ERR! stack     at Socket.<anonymous> (internal/child_process.js:319:11)gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! stack     at Socket.emit (events.js:169:7)
gyp 
ERR! stack     at Pipe._onclose (net.js:475:12)gyp ERR! System Linux 3.4.6
gyp ERR! command "/share/MD0_DATA/.qpkg/nodejs/node-v4.4.0-linux-x86/bin/node" "/share/MD0_DATA/.qpkg/nodejs/node-v4.4.0-linux-x86/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /share/MD0_DATA/alex/iobroker/node_modules/iobroker.homekit/node_modules/hap-nodejs/node_modules/curve25519
gyp ERR! 
node -v v4.4.0gyp ERR! node-gyp -v v3.3.0

gyp ERR! not ok 
gyp

ERR!
 configure error 
gyp
 ERR! stack Error: Command failed: /usr/local/bin/python2 -c import platform; print(platform.python_version());
gyp ERR! stack
 Traceback (most recent call last):gyp ERR! stack   File "<string>", line 1, in <module>
gyp ERR! stack   File "/root/daily_build/4.2.0/Model/TS-459/../../SysUtil/Python-2.7.5-cross/install_path_full/lib/python2.7/platform.py", line 116, in <module>
gyp ERR! stack ImportError: No module named string
gyp ERR! stack 
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:213:12)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:827:16)
gyp ERR! stack     at Socket.<anonymous> (internal/child_process.js:319:11)
gyp 
ERR! stack     at emitOne (events.js:77:13)gyp ERR! stack     at Socket.emit (events.js:169:7)
gyp ERR! stack     at Pipe._onclose (net.js:475:12)
gyp ERR! 
System Linux 3.4.6gyp ERR! command "/share/MD0_DATA/.qpkg/nodejs/node-v4.4.0-linux-x86/bin/node" "/share/MD0_DATA/.qpkg/nodejs/node-v4.4.0-linux-x86/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR! 
cwd /share/MD0_DATA/alex/iobroker/node_modules/iobroker.homekit/node_modules/hap-nodejs/node_modules/srp/node_modules/bignumgyp ERR! node -v v4.4.0
gyp ERR! node-gyp -v v3.3.0
gyp ERR! not ok 

gyp

ERR! 
configure error

gyp
 ERR! stack Error: Command failed: /usr/local/bin/python2 -c import platform; print(platform.python_version());
gyp
 ERR! stack Traceback (most recent call last):gyp ERR! stack   File "<string>", line 1, in <module>
gyp ERR! stack   File "/root/daily_build/4.2.0/Model/TS-459/../../SysUtil/Python-2.7.5-cross/install_path_full/lib/python2.7/platform.py", line 116, in <module>
gyp ERR! stack ImportError: No module named string
gyp ERR! stack 
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:213:12)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:827:16)
gyp ERR! stack     at Socket.<anonymous> (internal/child_process.js:319:11)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp 
ERR! stack     at Socket.emit (events.js:169:7)gyp ERR! stack     at Pipe._onclose (net.js:475:12)
gyp ERR! System Linux 3.4.6

gyp

ERR!
 command "/share/MD0_DATA/.qpkg/nodejs/node-v4.4.0-linux-x86/bin/node" "/share/MD0_DATA/.qpkg/nodejs/node-v4.4.0-linux-x86/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"gyp ERR! cwd /share/MD0_DATA/alex/iobroker/node_modules/iobroker.homekit/node_modules/hap-nodejs/node_modules/ed25519
gyp ERR! node -v v4.4.0
gyp ERR! node-gyp -v v3.3.0
gyp ERR! not ok 

gyp

ERR! configure error 
gyp
 ERR! stack Error: Command failed: /usr/local/bin/python2 -c import platform; print(platform.python_version());
gyp ERR! stack Traceback (most recent call last):gyp ERR! stack
   File "<string>", line 1, in <module>gyp ERR! stack   File "/root/daily_build/4.2.0/Model/TS-459/../../SysUtil/Python-2.7.5-cross/install_path_full/lib/python2.7/platform.py", line 116, in <module>
gyp ERR! stack ImportError: No module named string
gyp
 ERR! stack gyp ERR! stack     at ChildProcess.exithandler (child_process.js:213:12)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:827:16)
gyp ERR! stack     at Socket.<anonymous> (internal/child_process.js:319:11)
gyp 
ERR! stack     at emitOne (events.js:77:13)gyp ERR! stack     at Socket.emit (events.js:169:7)
gyp 
ERR! stack     at Pipe._onclose (net.js:475:12)gyp ERR! System Linux 3.4.6

gyp ERR! command "/share/MD0_DATA/.qpkg/nodejs/node-v4.4.0-linux-x86/bin/node" "/share/MD0_DATA/.qpkg/nodejs/node-v4.4.0-linux-x86/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"gyp ERR!
 cwd /share/MD0_DATA/alex/iobroker/node_modules/iobroker.homekit/node_modules/hap-nodejs/node_modules/mdnsgyp ERR! node -v v4.4.0
gyp 
ERR! node-gyp -v v3.3.0gyp ERR! not ok 

npm ERR! Linux 3.4.6
npm ERR! argv "/share/MD0_DATA/.qpkg/nodejs/node-v4.4.0-linux-x86/bin/node" "/share/MD0_DATA/.qpkg/nodejs/node/bin/npm" "install" "iobroker.homekit" "--production" "--prefix" "/share/MD0_DATA/alex/iobroker"npm
 ERR! node v4.4.0npm ERR!
 npm  v2.14.20
npm 
ERR! code ELIFECYCLE
npm
 ERR! curve25519@1.1.0 install: `node-gyp rebuild`
npm 
ERR!
 Exit status 1
npm ERR! npm ERR! Failed at the curve25519@1.1.0 install script 'node-gyp rebuild'.
npm ERR!
 This is most likely a problem with the curve25519 package,npm 
ERR! not with npm itself.npm ERR!
 Tell the author that this fails on your system:npm ERR!     node-gyp rebuild
npm ERR!
 You can get information on how to open an issue for this project with:npm 
ERR!     npm bugs curve25519
npm
 ERR! Or if that isn't available, you can get their info via:
npm 
ERR!
 npm 
ERR!     npm owner ls curve25519npm
 ERR!
 There is likely additional logging output above.

npm ERR! Please include the following file with any support request:npm ERR!     /share/MD0_DATA/alex/npm-debug.log

ERROR: host.BigBuddy Cannot install iobroker.homekit: 1
ERROR: process exited with code 25

**Comment by aski71** [comment]
Hallo,
irgendwer hier, der helfen kann? :-O
Danke!

**Comment by husky-koglhof** [comment]
Hallo, war die ganze Woche unterwegs, bin grade dabei, meine Punkte abzuarbeiten.

Welches OS, welche Node / NPM Version hast du im Einsatz?

LG Christian

**Comment by aski71** [comment]
Hallo Christian,
es läuft bei mir auf einem QNAP System (Linux) mit node-v4.4.0-linux-x86 und ppm 2.14.20.
LG Alex

**Comment by husky-koglhof** [comment]
Hallo, sieht für mich auf die schnelle nach diesem Fehler aus:

...Did you run sudo apt-get install libavahi-compat-libdnssd-dev before npm rebuild?...

https://github.com/KhaosT/HAP-NodeJS/issues/3

Kannst du mal versuchen, das dementsprechend anzupassen?
Wenn das bei dir so funktioniert, werde ich das in den Adapter so einbauen.

LG Christian

**Comment by aski71** [comment]
Sorry, aber auf einem QNAP gibt es weder sudo, noch apt-get. :-/

**Comment by aski71** [comment]
So. Gerade neu auf einem Raspberry installiert. Ähnliches Problem wie oben.
Nach apt-get install libavahi-compat-libdnssd-dev: Installation problemlos durchgelaufen.

**Comment by husky-koglhof** [comment]
Cool, das heißt es funktioniert grundsätzlich.
Bez. Qnap, wie installiert man dort zusätzliche Pakete?
Ist das ein Debian/RedHat/Properitäres Linux?

**Comment by emmpee** [comment]
Hallo Husky,
habe auch ein Installationsproblem wie aski vor einem Jahr. Raspi 2 mit Jessie light läuft bei mir. Es ist auch nur iobroker drauf. Vielleicht siehst Du ja was, das mir weiterhilft. Wäre super.

[npm-debug.txt](https://github.com/husky-koglhof/ioBroker.homekit/files/1090412/npm-debug.txt)

**Comment by Apollon77** [comment]
275 verbose stack Error: not found: git

Bitte "apt-get install git" und dann nochmals versuchen

**Comment by emmpee** [comment]
Installation hat funktioniert, danke. Aaaaaaber....der Adapter in iobroker läuft nicht wirklich. ich hänge mal einen Auszug aus dem Log an.

host.raspberrypi	2017-06-21 14:31:27.663	info	Restart adapter system.adapter.homekit2.0 because enabled
host.raspberrypi	2017-06-21 14:31:27.661	error	instance system.adapter.homekit2.0 terminated with code 0 (OK)
homekit2.0	2017-06-21 14:31:27.562	error	Error: Cannot find module 'hap-nodejs/node_modules/node-persist' at Function.Module._resolveFilename (module.js:469:15) at Function.Module._load (module.js:417:25) at Module.require (module.js:497:17) at require (internal/module.js:20:19) at main (/opt/iobroker/node_modules/iobroker.homekit2/main.js:215:19) at /opt/iobroker/node_modules/iobroker.homekit2/main.js:18:13 at Socket. (/opt/iobroker/node_modules/iobroker.homekit2/main.js:200:60) at Socket.onack (/opt/iobroker/node_modules/socket.io-client/lib/socket.js:312:9) at Socket.onpacket (/opt/iobroker/node_modules/socket.io-client/lib/socket.js:236:12) at Manager. (/opt/iobroker/node_modules/component-bind/index.js:21:15)
homekit2.0	2017-06-21 14:31:27.561	error	uncaught exception: Cannot find module 'hap-nodejs/node_modules/node-persist'
homekit2.0	2017-06-21 14:31:27.561	info	hap-nodejs starting...
homekit2.0	2017-06-21 14:31:27.559	debug	received all objects
homekit2.0	2017-06-21 14:31:27.181	debug	received all states
homekit2.0	2017-06-21 14:31:26.746	debug	requesting all objects
homekit2.0	2017-06-21 14:31:26.745	debug	requesting all states
homekit2.0	2017-06-21 14:31:26.744	info	starting. Version 0.1.6 in /opt/iobroker/node_modules/iobroker.homekit2, node: v6.11.0
host.raspberrypi	2017-06-21 14:31:22.925	info	instance system.adapter.homekit2.0 started with pid 815
host.raspberrypi	2017-06-21 14:30:52.889	info	Restart adapter system.adapter.homekit2.0 because enabled
host.raspberrypi	2017-06-21 14:30:52.887	error	instance system.adapter.homekit2.0 terminated with code 0 (OK)
homekit2.0	2017-06-21 14:30:52.818	info	terminating
homekit2.0	2017-06-21 14:30:52.767	error	at Manager. (/opt/iobroker/node_modules/component-bind/index.js:21:15)
homekit2.0	2017-06-21 14:30:52.767	error	at Socket.onpacket (/opt/iobroker/node_modules/socket.io-client/lib/socket.js:236:12)
homekit2.0	2017-06-21 14:30:52.767	error	at Socket.onack (/opt/iobroker/node_modules/socket.io-client/lib/socket.js:312:9)
homekit2.0	2017-06-21 14:30:52.767	error	at Socket. (/opt/iobroker/node_modules/iobroker.homekit2/main.js:200:60)
homekit2.0	2017-06-21 14:30:52.767	error	at /opt/iobroker/node_modules/iobroker.homekit2/main.js:18:13
homekit2.0	2017-06-21 14:30:52.767	error	at main (/opt/iobroker/node_modules/iobroker.homekit2/main.js:215:19)
homekit2.0	2017-06-21 14:30:52.767	error	at require (internal/module.js:20:19)
homekit2.0	2017-06-21 14:30:52.767	error	at Module.require (module.js:497:17)
homekit2.0	2017-06-21 14:30:52.767	error	at Function.Module._load (module.js:417:25)
homekit2.0	2017-06-21 14:30:52.767	error	at Function.Module._resolveFilename (module.js:469:15)
homekit2.0	2017-06-21 14:30:52.767	error	Error: Cannot find module 'hap-nodejs/node_modules/node-persist'
homekit2.0	2017-06-21 14:30:52.766	error	uncaught exception: Cannot find module 'hap-nodejs/node_modules/node-persist'
homekit2.0	2017-06-21 14:30:52.723	info	hap-nodejs starting...
homekit2.0	2017-06-21 14:30:52.711	debug	received all objects
homekit2.0	2017-06-21 14:30:52.408	debug	received all states
homekit2.0	2017-06-21 14:30:52.017	debug	requesting all objects
homekit2.0	2017-06-21 14:30:52.009	debug	requesting all states
homekit2.0	2017-06-21 14:30:51.991	info	starting. Version 0.1.6 in /opt/iobroker/node_modules/iobroker.homekit2, node: v6.11.0
homekit2.0	2017-06-21 14:30:51.814	debug	statesDB connected
homekit2.0	2017-06-21 14:30:51.514	debug	objectDB connected
admin.0	2017-06-21 14:30:51.022	info	Repository received successfully.
host.raspberrypi	2017-06-21 14:30:48.376	info	Update repository 'default' under 'http://download.iobroker.net/sources-dist.json'
admin.0	2017-06-21 14:30:48.168	info	Request actual repository...
admin.0	2017-06-21 14:30:47.957	info	received all objects
admin.0	2017-06-21 14:30:47.687	info	received all states
admin.0	2017-06-21 14:30:47.542	info	system.adapter.admin.0: logging true
discovery.0	2017-06-21 14:30:47.462	info	system.adapter.admin.0: logging true
host.raspberrypi	2017-06-21 14:30:47.425	info	instance system.adapter.homekit2.0 started with pid 801
admin.0	2017-06-21 14:30:47.351	info	Change log subscriber state: true
discovery.0	2017-06-21 14:30:46.678	info	starting. Version 0.4.0 in /opt/iobroker/node_modules/iobroker.discovery, node: v6.11.0
admin.0	2017-06-21 14:30:46.429	info	Use link 'http://localhost:8081' to configure.
admin.0	2017-06-21 14:30:46.428	info	http server listening on port 8081
admin.0	2017-06-21 14:30:46.416	info	requesting all objects
admin.0	2017-06-21 14:30:46.409	info	requesting all states
admin.0	2017-06-21 14:30:46.185	info	starting. Version 1.7.6 in /opt/iobroker/node_modules/iobroker.admin, node: v6.11.0
host.raspberrypi	2017-06-21 14:30:43.353	info	instance system.adapter.discovery.0 started with pid 787
host.raspberrypi	2017-06-21 14:30:29.974	info	instance system.adapter.admin.0 started with pid 781
host.raspberrypi	2017-06-21 14:30:29.782	info	starting 3 instances
host.raspberrypi	2017-06-21 14:30:29.747	info	3 instances found
host.raspberrypi	2017-06-21 14:30:29.693	info	InMemoryDB connected
host.raspberrypi	2017-06-21 14:30:29.668	info	inMem-objects listening on port 9001
host.raspberrypi	2017-06-21 14:30:29.498	info	inMem-states listening on port 9000
host.raspberrypi	2017-06-21 14:30:29.239	info	ip addresses: 192.168.178.27 fe80::a4f7:bce1:5e64:45a8
host.raspberrypi	2017-06-21 14:30:29.235	info	hostname: raspberrypi, node: v6.11.0
host.raspberrypi	2017-06-21 14:30:29.232	info	Copyright (c) 2014-2017 bluefox, hobbyquaker
host.raspberrypi	2017-06-21 14:30:29.204	info	iobroker.js-controller version 1.0.3 js-controller starting
host.raspberrypi	2017-06-21 14:30:05.514	info	terminated
host.raspberrypi	2017-06-21 14:30:05.462	info	All instances are stopped.
host.raspberrypi	2017-06-21 14:30:05.461	info	instance system.adapter.admin.0 terminated with code 0 (OK)
host.raspberrypi	2017-06-21 14:30:05.344	info	All instances are stopped.
host.raspberrypi	2017-06-21 14:30:05.342	info	instance system.adapter.discovery.0 terminated with code 0 (OK)
admin.0	2017-06-21 14:30:05.323	info	terminating http server on port 8081
discovery.0	2017-06-21 14:30:05.319	info	terminating
host.raspberrypi	2017-06-21 14:30:05.301	warn	stopInstance system.adapter.homekit2.0 not running
host.raspberrypi	2017-06-21 14:30:05.299	info	stopInstance system.adapter.homekit2.0
host.raspberrypi	2017-06-21 14:30:05.298	info	stopInstance system.adapter.discovery.0 killing pid 787
host.raspberrypi	2017-06-21 14:30:05.297	info	stopInstance system.adapter.discovery.0
host.raspberrypi	2017-06-21 14:30:05.295	info	stopInstance system.adapter.admin.0 killing pid 780
host.raspberrypi	2017-06-21 14:30:05.294	info	stopInstance system.adapter.admin.0
host.raspberrypi	2017-06-21 14:30:05.286	info	received SIGTERM
host.raspberrypi	2017-06-21 14:29:59.874	info	Restart adapter system.adapter.homekit2.0 because enabled
host.raspberrypi	2017-06-21 14:29:59.873	error	instance system.adapter.homekit2.0 terminated with code 0 (OK)
homekit2.0	2017-06-21 14:29:59.836	info	terminating

Kannst Du damit was anfangen?

**Comment by Apollon77** [comment]
Ich denke lass homekit Adapter bitte sein und gehe auf yahka Adapter!! Der ist aktiv in der Entwicklung momentan und im Forum gut supportet!!

**Comment by emmpee** [comment]
Alles klar, ich danke Dir.
